package com.majalis.asset;

public enum AssetEnum {
	UI_SKIN("uiskin.json"),
	SPLASH_SCREEN("Splash.png"),
	
	MAIN_MENU_SCREEN("MainMenuScreen.jpg"),
	
	DEFAULT_BACKGROUND("DefaultBackground.jpg"),
	GAME_TYPE_BACKGROUND("GameTypeSelect.jpg"),
	CLASS_SELECT_BACKGROUND("ClassSelect.jpg"),
	DRYAD_BACKGROUND("DryadApple.jpg"),
	STICK_BACKGROUND("StickEncounter.jpg"),
	CABIN_BACKGROUND("WoodsCottage.jpg"),
	BURNING_FORT_BG("BurningFort.jpg"),
	TOWN_BG("town/TownBG.jpg"),
	
	WORLD_MAP_UI("worldmap/CharacterInfo.png"),
	WORLD_MAP_HOVER("worldmap/HoverBox.png"),
	ARROW("worldmap/Arrow.png"),
	MOUNTAIN_ACTIVE("worldmap/MountainNode0.png"),
	FOREST_ACTIVE("worldmap/ForestNode1.png"),
	FOREST_INACTIVE("worldmap/ForestNode0.png"),
	ENCHANTED_FOREST("worldmap/ForestNode0.png"),
	GRASS0("worldmap/BaseGrass0.png"),
	GRASS1("worldmap/BaseGrass1.png"),
	GRASS2("worldmap/BaseGrass2.png"),
	CLOUD("worldmap/Cloud.png"),
	APPLE("worldmap/Apple.png"),
	MEAT("worldmap/Meat.png"),
	ROAD("worldmap/Road.png"),
	CASTLE("worldmap/Castle.png"),
	COTTAGE("worldmap/CottageNode0.png"),
	TOWN("worldmap/TownNode0.png"),
	CHARACTER_ANIMATION("worldmap/TinySprite.png"),
	
	CHARACTER_SCREEN("ClassSelect.jpg"),
	
	WEREBITCH("enemies/WerebitchBasic.png"),
	HARPY("enemies/Harpy.png"),
	HARPY_FELLATIO("enemies/HarpyFellatio.png"),
	BRIGAND("enemies/Brigand.png"),
	BRIGAND_ORAL("enemies/BrigandOral.jpg"),
	SLIME("enemies/HeartSlime.png"), 
	SLIME_DOGGY("enemies/HeartSlimeLoveDart.png"), 
	CENTAUR("enemies/HorseCentaur.png"),
	UNICORN("enemies/UnicornCentaur.png"),
	GOBLIN("enemies/GoblinFuta.png"),
	GOBLIN_FACE_SIT("enemies/GoblinFaceSit.png"),
	TRAP_BONUS("enemies/TrapBonus.jpg"), 
	
	HEALTH_ICON_0("battle/Heart0.png"),
	STAMINA_ICON_0("battle/Stam0.png"),
	BALANCE_ICON_0("battle/Scale0.png"),
	MANA_ICON_0("battle/Eye0.png"),
	HEALTH_ICON_1("battle/Heart1.png"),
	STAMINA_ICON_1("battle/Stam1.png"),
	BALANCE_ICON_1("battle/Scale1.png"),
	MANA_ICON_1("battle/Eye1.png"),
	HEALTH_ICON_2("battle/Heart2.png"),
	STAMINA_ICON_2("battle/Stam2.png"),
	BALANCE_ICON_2("battle/Scale2.png"),
	MANA_ICON_2("battle/Eye2.png"),
	HEALTH_ICON_3("battle/Heart3.png"),
	STAMINA_ICON_3("battle/Stam3.png"),
	BALANCE_ICON_3("battle/Scale3.png"),
	MANA_ICON_3("battle/Eye3.png"),
	
	BATTLE_SKIN("battle/battleui.json"),
	CHARACTER_POTRAIT("battle/Neutral.png"),
	FOREST_BG("battle/ForestBG.jpg"),
	PLAINS_BG("battle/AbandonedField.jpg"),
	ENCHANTED_FOREST_BG("battle/MushroomForest.jpg"),
	BATTLE_UI("battle/Treeframe.png"),
	BATTLE_HOVER("battle/SkillHover.png"),
	BATTLE_TEXTBOX("battle/TextBox.png"),
	TEXT_BOX("battle/NameBox.png"),
	
	SHOPKEEP("characters/AppleKeep.png"),
	TRAINER("characters/HeavyTrainer1.png"),
	MERI_SILHOUETTE("characters/Witch.png"),
	SILHOUETTE("characters/Silhouette.png"),
	
	AIRBORNE("stances/Airborne.png"),
	ANAL("stances/Anal.png"),
	BALANCED("stances/Balanced.png"),
	BLITZ("stances/Blitz.png"),
	CASTING("stances/Casting.png"),
	COWGIRL("stances/Cowgirl.png"),
	DEFENSIVE("stances/Defensive.png"),
	DOGGY("stances/Doggy.png"),
	ERUPT("stances/Erupt.png"),
	FACE_SITTING("stances/Facesitting.png"),
	FELLATIO("stances/Fellatio.png"),
	FULL_NELSON("stances/FullNelson.png"),
	HANDY("stances/Handy.png"),
	KNEELING("stances/Kneeling.png"),
	KNOTTED("stances/Knotted.png"),
	OFFENSIVE("stances/Offensive.png"),
	PRONE("stances/Prone.png"),
	SIXTY_NINE("stances/SixyNine.png"),
	STANDING("stances/Standing.png"),
	SUPINE("stances/Supine.png"),
	
	STANCE_ARROW("stances/ChevronArrow.png"),
	
	STRENGTH("stats/Strength.png"),
	ENDURANCE("stats/Endurance.png"),
	AGILITY("stats/Agility.png"),
	PERCEPTION("stats/Perception.png"),
	MAGIC("stats/Magic.png"),
	CHARISMA("stats/Charisma.png"), 
	
	SLASH("animation/ClawAttack.png"),
	
	GAME_OVER_GAPE("GameOverButt.jpg"),
	GAME_OVER_TUCKERED("GameOverTuckered.jpg"),
	GAME_OGRE("PostOgre.jpg"),
	// sounds
	BUTTON_SOUND("sound.wav"),
	CLICK_SOUND("node_sound.wav"),
	INTRO_SOUND("sounds/IntroSound.wav"),
	EQUIP("sounds/Equip.wav"),
	LOUD_LAUGH("sounds/LoudLaugh.wav"),
	UNPLUGGED_POP("sounds/UnpluggedPop.wav"),
	MOUTH_POP("sounds/MouthPop.wav"),
	SLIPPY_01("sounds/Slippy01.wav"),
	SLOPPY_01("sounds/Sloppy01.wav"),
	ATTACK_SOUND("sounds/AttackSound.wav"),
	HIT_SOUND("sounds/HitSound.wav"),
	SWORD_SLASH_SOUND("sounds/SwordSlash.wav"),
	FIREBALL_SOUND("sounds/Fireball.wav"),
	INCANTATION("sounds/Incantation.wav"),
	THWAPPING("sounds/Thwapping.wav"),
	SMUG_LAUGH("sounds/FemaleSmugLaugh.wav"),
	OGRE("sounds/Ogre.wav"),
	// music
	MAIN_MENU_MUSIC("music/MainMenuMusic.mp3"),
	ENCOUNTER_MUSIC("music/EncounterMusic.mp3"),
	SHOP_MUSIC("music/ShopkeepMusic.mp3"),
	TRAINER_MUSIC("music/TrainerMusic.mp3"),
	HOVEL_MUSIC("music/HovelMusic.mp3"),
	WEREWOLF_MUSIC("music/WerewolfMusic.mp3"),
	HEAVY_MUSIC("music/Mechanolith.mp3"),
	WORLD_MAP_MUSIC("music/WorldMapMusic.mp3"),
	BATTLE_MUSIC("music/BattleMusic.mp3"),
	WAVES("music/Waves.wav")
	;
	
	private final String path;

	AssetEnum(String path) {
	    this.path = path;
	 }
	public String getPath(){return path;}
}
